### PR TITLE
fix warning: https://github.com/johnsonjh/duma/issues/76

### PR DESCRIPTION
**Pull request by hayguen**

### CODE REVIEW

**Review by johnsonjh — APPROVED** [review]
Ok

**Comment by johnsonjh** [comment]
I'll look into excluding the test cases cases from analysis as a more general rule.

**Comment by hayguen** [comment]
could be done .. but in this case, we might probably oversee a new not intended one?

**Comment by johnsonjh** [comment]
True - not sure what's the best approach just yet

**Comment by hayguen** [comment]
would think, we don't change the examples that often.
but, in fact, i have one more example in mind (better: demonstration), to compare **performance** with sort of number crunching.
just curious about what time factors we would get compared to gcc address sanitizer, but also valgrind.

**Comment by johnsonjh** [comment]
it's my experience Duma > valgrind in terms of performance, would be nice to quantify it.

I very much like how Go does benchmarking - I'll look to see if anything similar exists for portable C

**Comment by hayguen** [comment]
> would be nice to quantify it.

exactly.


> I'll look to see if anything similar exists for portable C

don't think, that we need a portable solution - x86/64 Linux is sufficient - as valgrind isn't CPU/OS portable, and we just need a coarse idea of the difference:
simply call `time` from a shell script. if the demonstration is calculation for something over multiple seconds .. we should see the difference.

**Comment by johnsonjh** [comment]
**time**(*1*) is one of those places where POSIX is terrible.

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/time.html

> When the time utility was originally proposed to be included in the ISO POSIX-2:1993 standard, questions were raised about its suitability for inclusion on the grounds that it was not useful for conforming applications, specifically:
>
> The underlying CPU definitions from the System Interfaces volume of POSIX.1-2017 are vague, so the numeric output could not be compared accurately between systems or even between invocations.

Also, accurately timing with sub-second resolution is tricky even on the same platform between different C libraries, etc.

I'd prefer not to have a long test time - at least not unnecessarily. Maybe only run the benchmark as a part of a "benchmark" target.

🤔

**Comment by johnsonjh** [comment]
Moved discussion to https://github.com/johnsonjh/duma/issues/83

**Pull request merged**
